export const FETCH_AUTHORIZATION = "FETCH_AUTHORIZATION";
export const INITIATE_AUTH_FETCH = "INITIATE_AUTH_FETCH";
export const FETCH_MEMBER_OPTS = "FETCH_MEMBER_OPTS";
export const FETCH_MOVIEGOER_STATUS = "FETCH_MOVIEGOER_STATUS";
export const FETCH_GUEST_STATUS = "FETCH_GUEST_STATUS";