export const FETCH_AUTHORIZATION = "FETCH_AUTHORIZATION";
export const INITIATE_AUTH_FETCH = "INITIATE_AUTH_FETCH";
export const FETCH_MEMBER_OPTS = "FETCH_MEMBER_OPTS";
export const FETCH_OPTS_DESCRIPTIONS = "FETCH_OPTS_DESCRIPTIONS";