name: savepointlodge-web
services:
  frontend:
    build:
      context: .
    hostname: frontend
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DISCORD_AUTH_CLIENT_ID=${DISCORD_AUTH_CLIENT_ID}
      - DISCORD_AUTH_CLIENT_SECRET=${DISCORD_AUTH_CLIENT_SECRET}
      - AUTH_SESSION_SECRET=${AUTH_SESSION_SECRET}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_SENDER_ID=${FIREBASE_SENDER_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_CLIENT_PASSWORD=${FIREBASE_CLIENT_PASSWORD}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - AUTHORIZED_API_KEY=${AUTHORIZED_API_KEY}
      - GIPHY=${GIPHY}
    depends_on:
      redis:
        condition: service_healthy
    expose:
      - 8080

  redis:
    image: redis:latest
    restart: always
    volumes:
      - db-data:/var/lib/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    expose:
      - 6379

  server:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/letsencrypt/live/savepointlodge.com/
    ports:
      - 80:80
      - 443:443

volumes: 
  db-data:

