services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      tags:
        - "spl-web:main"
    env_file:
      - .env
    expose:
      - "3000"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
