services:
  web:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - PUID=1000
      - PGID=1000
    env_file:
      - '.env'
    ports:
      - "3000:3000"
      - ":8080"
    volumes:
      - "/Users/jclaus/code/save-point-lodge-discord-web:/data"
