services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=prod_test
    ports:
      - "3000:3000"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
